name: Robot Loteria Semanal

on:
  schedule:
    # Se ejecuta los Martes y Viernes a las 17:00 (Hora UTC)
    - cron: '0 17 * * 2,5'
  # Este comando es el que te permite darle al bot√≥n "Run workflow" para probar
  workflow_dispatch: 

jobs:
  ejecutar-robot:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Descargar codigo
      uses: actions/checkout@v4

    - name: 2. Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 3. Instalar librerias necesarias
      run: pip install requests

    - name: 4. Ejecutar el robot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py
      
